version: '3.3'
services:
  test-app:
    build: .
    container_name: circus-test
    hostname: circus-test
    image: mvkvl/circus
    volumes:
        - ./circus.conf:/etc/circus.conf
    ports:
      - 10080:8888
    # stdin_open: true
    # tty: true
