version: '3.3'

networks:
  graf:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: monitor1
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:

  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: arm32v7/influxdb
    volumes:
        - /docker/data/influxdb:/var/lib/influxdb
        - /docker/conf/influxdb/influxdb.conf:/etc/influxdb.conf:ro
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      graf:
        ipv4_address: 172.30.0.31
    stdin_open: true
    tty: true

  redis:
    container_name: redis
    hostname: redis
    image: arm32v7/redis
    volumes:
      - /docker/data/redis:/data
    ports:
      - 6379:6379
    networks:
      graf:
        ipv4_address: 172.30.0.32
    depends_on:
      - influxdb

  monitoring:
    container_name: monitoring
    hostname: monitoring
    image: mvkvl/monitoring-armhf
    volumes:
        - /docker/conf/monitor/rig-monitor/circus.conf:/etc/circus.conf
        - /docker/conf/monitor/rig-monitor/bin:/service/bin
        - /docker/conf/monitor/rig-monitor/lib:/service/lib
        - /docker/conf/monitor/rig-monitor/conf:/service/conf
        - /docker/conf/monitor/rig-tools/lib:/service/lib/rig
    privileged: true
    networks:
      graf:
        ipv4_address: 172.30.0.35
    depends_on:
      - influxdb
      - redis

  chronograf:
    container_name: chronograf
    hostname: chronograf
    image: arm32v7/chronograf
    volumes:
      - /docker/data/chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    networks:
      graf:
        ipv4_address: 172.30.0.33
    stdin_open: true
    tty: true
    depends_on:
      - monitoring

  grafana:
    container_name: grafana
    hostname: grafana
    image: mvkvl/grafana-armhf:5.3.0-beta1
    volumes:
        - /docker/data/grafana/plugins:/var/lib/grafana/plugins/
        - /docker/data/grafana/data:/var/lib/grafana
        - /tmp/docker/grafana:/var/log/grafana/
    ports:
      - 3000:3000
    networks:
      graf:
        ipv4_address: 172.30.0.34
    stdin_open: true
    tty: true
    depends_on:
      - chronograf




#  telegraf:
#    container_name: telegraf
#    hostname: telegraf
#    image: arm32v7/telegraf
#    volumes:
#        - /docker/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    stdin_open: true
#    tty: true
#    depends_on:
#      - chronograf
#    networks:
#      graf:
#        ipv4_address: 172.30.0.34
