version: '3.3'

networks:
  graf:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: monitor1
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:

  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: hypriot/rpi-influxdb
    volumes:
        - /docker/data/influxdb:/data
        - /docker/conf/influxdb/influxdb.conf:/etc/influxdb.conf:ro
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      graf:
        ipv4_address: 172.30.0.31
    stdin_open: true
    tty: true

  chronograf:
    container_name: chronograf
    hostname: chronograf
    image: arm32v7/chronograf
    volumes:
      - /docker/data/chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    networks:
      graf:
        ipv4_address: 172.30.0.32
    stdin_open: true
    tty: true
    depends_on:
      - influxdb

  grafana:
    container_name: grafana
    hostname: grafana
    image: mvkvl/grafana-armhf:5.3.0-beta1
    volumes:
        - /docker/data/grafana/plugins:/var/lib/grafana/plugins/
        - /docker/data/grafana/data:/var/lib/grafana
        - /tmp/docker/grafana:/var/log/grafana/
    ports:
      - 3000:3000
    networks:
      graf:
        ipv4_address: 172.30.0.33
    stdin_open: true
    tty: true
    depends_on:
      - chronograf


#  telegraf:
#    container_name: telegraf
#    hostname: telegraf
#    image: arm32v7/telegraf
#    volumes:
#        - /docker/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    stdin_open: true
#    tty: true
#    depends_on:
#      - chronograf
#    networks:
#      graf:
#        ipv4_address: 172.30.0.34
